### ISSUE TITLE
limits

### ISSUE THREAD

**Issue by AlexandreMertens** [blinkseb/TMultiDrawTreePlayer#1]
When I compile, I have an error saying:
[amertens@ingrid-ui1 plotUtils]$ ./compile.sh 
TMultiDrawTreePlayer/TMultiDrawTreePlayer.cxx: In member function 'virtual bool TMultiDrawTreePlayer::execute()':
TMultiDrawTreePlayer/TMultiDrawTreePlayer.cxx:280:27: error: 'numeric_limits' is not a member of 'std'
     Long64_t firstentry = std::numeric_limits<Long64_t>::max();
                           ^
TMultiDrawTreePlayer/TMultiDrawTreePlayer.cxx:280:55: error: expected primary-expression before '>' token
     Long64_t firstentry = std::numeric_limits<Long64_t>::max();
                                                       ^
TMultiDrawTreePlayer/TMultiDrawTreePlayer.cxx:280:56: error: '::max' has not been declared
     Long64_t firstentry = std::numeric_limits<Long64_t>::max();
                                                        ^
TMultiDrawTreePlayer/TMultiDrawTreePlayer.cxx:280:56: note: suggested alternative:
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/gcc/4.9.1-cms/include/c++/4.9.1/vector:60:0,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/TGenericClassInfo.h:15,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/Rtypes.h:215,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/TObject.h:31,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/TNamed.h:26,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/TBranch.h:28,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/TTree.h:30,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_5/external/slc6_amd64_gcc491/bin/../../../../../../lcg/root/6.02.00-odfocd4/include/TTreePlayer.h:31,
                 from TMultiDrawTreePlayer/TMultiDrawTreePlayer.h:31,
                 from TMultiDrawTreePlayer/TMultiDrawTreePlayer.cxx:1:
/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/gcc/4.9.1-cms/include/c++/4.9.1/bits/stl_algobase.h:261:5: note:   'std::max'
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
So, I think that limit should be added to the header. Is it correct?

**Comment by blinkseb** [comment]
Should be fixed by f10f215dd6f8a55d62c36e17481bbe9c42500ee2
